Update structs.md
dlang-tour/french pull request #61
Opened 2017-06-26 13:21 UTC by lmartelli

Fix translation.

2017-06-27 10:45 UTC, BBasile commented on basics/structs.md
> +Déclarer une méthode `const` permet de l'appeller sur un objet `const` ou `immutable`, mais garantie également aux appelant que la méthode ne changera pas l'état de l'objet.
appelant__s__ car pluriel par `aux`

2017-06-27 10:46 UTC, ghost requested changes
doit changer la faute de pluriel

2017-06-27 17:40 UTC, schlupa commented on basics/structs.md
> +Déclarer une méthode `const` permet de l'appeler sur un objet `const` ou `immutable`, mais garantie également aux appelants que la méthode ne changera pas l'état de l'objet.
appelants s'accorde, ce n'est pas un verbe au participe présent mais un substantif.

2017-06-27 17:41 UTC, schlupa commented on basics/structs.md
> +Cependant, avec `alias this` ou les `mixins`, on peut facilement obtenir du polymorphisme.
lol

2017-07-01 04:28 UTC, ghost approved these changes

2017-07-01 04:28 UTC, merged